"use strict"

let Constants = module.exports = {}

Constants.CHECKS = {
	SWEARS:  ["damn","dyke","fuck","shit","@$$","amcik","andskota","arschloch","arse","asshole","assramer","atouche","ayir","b!+ch","b!tch","b17ch","b1tch","bastard","bi+ch","bi7ch","bitch","boiolas","bollock","breasts","buceta","butt-pirate","c0ck","cabron","cawk","cazzo","chink","chraa","chuj","cipa","clits","cock","cum","cunt","d4mn","dago","daygo","dego","dick","dike","dildo","dirsa","dupa","dziwka","ejackulate","ekrem","ekto","enculer","faen","fag","fanculo","fanny","fatass","fcuk","feces","feg","felcher","ficken","fitta","fitte","flikker","foreskin","fotze","fu(","fuk","futkretzn","fux0r","gay","gook","guiena","h0r","h4x0r","helvete","hoer","hoer","honkey","hore","huevon","hui","injun","jism","jizz","kanker","kawk","kike","klootzak","knulle","kraut","kuk","kuksuger","kurac","kurwa","kusi","kyrpä","l3i+ch","l3itch","lesbian","lesbo","mamhoon","masturbat","merd","merde","mibun","monkleigh","motherfucker","mouliewop","muie","mulkku","muschi","nazis","nepesaurio","nigga","nigger","nutsack","orospu","paska","pendejo","penis","perse","phuck","picka","pierdol","pillu","pimmel","pimpis","piss","pizda","poontsee","poop","porn","pr0n","preteen","preud","prick","pule","pusse","pussy","puta","puto","qahbeh","queef","queer","qweef","rautenberg","schaffer","scheiss","scheisse","schlampe","schmuck","screw","scrotum","sh!t","sharmuta","sharmute","shemale","shipal","shiz","skribz","skurwysyn","slut","smut","sphencter","spierdalaj","splooge","suka","teets","teez","testicles","tits","titties","titty","twat","twaty","vittu","votze","w00se","wank","wetback","whoar","whore","wichser","wop","zabourah","nazi","natzi","asswipe","sex","ƒuck","rape","fcking","nligger","shlt","hitler","rhape","hoe","pedo","vagina","puta","pute","fhag","nigg","niger","nigah","niguh","niqq","phaggot","ghey","ni99","biatch","orgasm","fcker","bytch","pussies","retard","ni66","n1gg","nlgg","niga","gringo","fhaggot","jewmad","ngger","ngga","fuhrer"],
	SPECIAL: ["!","@","#","$","%","^","&","*","(",")","-","_","=","+","\\","|","[","{","]","}",";",":","'",`"`,",","<",".",">","/","?","`","~"],
	IPS:     ["123.123.123.123","69.69.69.69"],
	IPMASKS: ["38.99.10","38.104.1"],
	IPRANGE: ["205.164.4.0-205.164.4.255"]
}